//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Kloby"",
            ""id"": ""c41b7f69-6222-4fec-ae81-19862e689323"",
            ""actions"": [
                {
                    ""name"": ""WASDMovement"",
                    ""type"": ""Value"",
                    ""id"": ""e3381597-5343-44df-bbc8-56c254618bf1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WASDPull"",
                    ""type"": ""Button"",
                    ""id"": ""c64445e2-e157-4748-9d4e-5ad157d7c5a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WASDPush"",
                    ""type"": ""Button"",
                    ""id"": ""97ec9098-7220-4063-9ca3-b0080814a377"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WASDboost"",
                    ""type"": ""Button"",
                    ""id"": ""558a0407-3d90-4d66-9c29-7d42f0659e39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowsMovement"",
                    ""type"": ""Value"",
                    ""id"": ""8eab9825-6b18-4fc7-a5ab-9cd8c190865f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ArrowsPush"",
                    ""type"": ""Button"",
                    ""id"": ""d1ecc0ea-de95-41fe-a3de-456e006c91d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowsPull"",
                    ""type"": ""Button"",
                    ""id"": ""950ac2b5-ed68-4b52-b617-22922fc5f288"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Arrowsboost"",
                    ""type"": ""Button"",
                    ""id"": ""b800577a-2b5d-40b3-bcc1-740661777dfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""324b2bdb-997b-4f62-b034-ccf301c9b55a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d1c09bfd-8e50-447f-89d4-34d3b6bf351f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""54a0fa01-a626-4a9f-9cf7-1ff2a47b53eb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c7fc4f47-e0e8-482d-a429-0641e99aee16"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e6bb4986-b9be-413a-a3da-9ebafeeefafa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ed5c5f52-48a8-41d0-a77f-eff868c02926"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3dc110b6-200e-4212-8c40-7201631021c4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d289dfbe-db4a-4de0-8fb5-d3243d7f5d5c"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9200ed9-e316-4825-862d-535c3af7896c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b48b4916-f4f2-4f95-a6ed-99c27ef8b50c"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsPush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf15c7da-909f-4c91-bc4e-195726debe55"",
                    ""path"": ""<Keyboard>/numpadPeriod"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsPull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcab6a1f-076d-4719-ab13-605aa3c2b0c2"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff5d5139-70e9-47c0-9bec-2b10b354d3ef"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a6890d61-4f78-40ca-9aa8-25bda8c4fa13"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""02dd2c3a-c250-4630-844c-cf05b0ed5283"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""96638af6-90b8-48c9-8589-5a1d2d260b64"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ca9f3703-a360-411f-9727-482ad9eb28a3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3df4d21f-cac1-4b46-b995-9a3192d5135b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e5741059-e6c1-4bda-8ced-906903fde8ba"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrowsboost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2a692c2-646d-4ab2-9c8c-cb6eca4988d6"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDboost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b9bdff0-f99e-4c3f-bb75-03f785bb4b1b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDboost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6c8a5f1-afcd-44c3-8026-643fc00d8fad"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Kloby1"",
            ""id"": ""60b674d0-1ddd-4bcd-875c-d5976e130026"",
            ""actions"": [
                {
                    ""name"": ""WASDMovement"",
                    ""type"": ""Value"",
                    ""id"": ""233eae3c-7084-4300-b97c-5391281f9d66"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WASDPull"",
                    ""type"": ""Button"",
                    ""id"": ""cb6d6ddb-20a5-424f-9bb8-a90df8d5ccb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WASDPush"",
                    ""type"": ""Button"",
                    ""id"": ""fd758a8b-ddf0-4a3d-9cf3-65e071e07a8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WASDboost"",
                    ""type"": ""Button"",
                    ""id"": ""8ce736f4-1d89-4a02-a60e-6d9ec5e73637"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowsMovement"",
                    ""type"": ""Value"",
                    ""id"": ""4b6b8ece-147b-4c18-a3da-2ae0c5a08f11"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ArrowsPush"",
                    ""type"": ""Button"",
                    ""id"": ""d27e9f0a-e1dd-417d-b106-2ad6e017f48d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowsPull"",
                    ""type"": ""Button"",
                    ""id"": ""60c8b373-1242-48e1-8ffc-923aa65fdb13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Arrowsboost"",
                    ""type"": ""Button"",
                    ""id"": ""03189774-57e1-4bc5-8c21-0f4be3a695ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""9779289d-4f91-4eb3-a66a-7404b56952ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2d421564-8897-4f15-8b79-da4e317cbe81"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eaa573af-0994-4081-8d93-26b745bf4c95"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6e66bb17-da0e-4a35-8bd8-d3a82e31cc11"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e2293c76-0016-4194-b13a-c089d73461aa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2087bed2-a15a-4df0-8c5d-10a86b7f5743"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""69a53368-6271-48ba-a0e0-9b3fca7346a4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba311074-8a75-4f3c-9e30-7775c119e7be"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""375c833b-c159-4a1d-a22e-473fbe9c19da"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0028c6ef-e565-4fd9-af06-72d1da9d6459"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsPush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e17d3e7-964f-4e08-820b-ea8e8c1a1aff"",
                    ""path"": ""<Keyboard>/numpadPeriod"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsPull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74779100-d698-4f3c-b371-c0358a188642"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aa1aacb-f56b-4b35-bf46-1c68ecc9c653"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDPull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f18a5358-1e8c-42b0-a2c1-9435d07aec66"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7f9a3c24-e93d-4be7-bcf1-180da2e1e61b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a6c18d40-563a-42c6-a2ca-bff846471f7f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d2e46281-1042-4781-ad13-f9844ae1e3ac"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""103f2497-6b46-4e87-af68-93b09c22550d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""05ea1266-fd2f-4d2f-af5f-51d5cced0ba0"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrowsboost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ac32034-ae2d-42d0-8af6-fd665ea1c66d"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDboost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06766e9b-0c34-446b-b71f-f7e28f7149c0"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASDboost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bf6fbd2-53ea-4e07-8789-bcd8a8562386"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Kloby
        m_Kloby = asset.FindActionMap("Kloby", throwIfNotFound: true);
        m_Kloby_WASDMovement = m_Kloby.FindAction("WASDMovement", throwIfNotFound: true);
        m_Kloby_WASDPull = m_Kloby.FindAction("WASDPull", throwIfNotFound: true);
        m_Kloby_WASDPush = m_Kloby.FindAction("WASDPush", throwIfNotFound: true);
        m_Kloby_WASDboost = m_Kloby.FindAction("WASDboost", throwIfNotFound: true);
        m_Kloby_ArrowsMovement = m_Kloby.FindAction("ArrowsMovement", throwIfNotFound: true);
        m_Kloby_ArrowsPush = m_Kloby.FindAction("ArrowsPush", throwIfNotFound: true);
        m_Kloby_ArrowsPull = m_Kloby.FindAction("ArrowsPull", throwIfNotFound: true);
        m_Kloby_Arrowsboost = m_Kloby.FindAction("Arrowsboost", throwIfNotFound: true);
        m_Kloby_Quit = m_Kloby.FindAction("Quit", throwIfNotFound: true);
        // Kloby1
        m_Kloby1 = asset.FindActionMap("Kloby1", throwIfNotFound: true);
        m_Kloby1_WASDMovement = m_Kloby1.FindAction("WASDMovement", throwIfNotFound: true);
        m_Kloby1_WASDPull = m_Kloby1.FindAction("WASDPull", throwIfNotFound: true);
        m_Kloby1_WASDPush = m_Kloby1.FindAction("WASDPush", throwIfNotFound: true);
        m_Kloby1_WASDboost = m_Kloby1.FindAction("WASDboost", throwIfNotFound: true);
        m_Kloby1_ArrowsMovement = m_Kloby1.FindAction("ArrowsMovement", throwIfNotFound: true);
        m_Kloby1_ArrowsPush = m_Kloby1.FindAction("ArrowsPush", throwIfNotFound: true);
        m_Kloby1_ArrowsPull = m_Kloby1.FindAction("ArrowsPull", throwIfNotFound: true);
        m_Kloby1_Arrowsboost = m_Kloby1.FindAction("Arrowsboost", throwIfNotFound: true);
        m_Kloby1_Quit = m_Kloby1.FindAction("Quit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Kloby
    private readonly InputActionMap m_Kloby;
    private IKlobyActions m_KlobyActionsCallbackInterface;
    private readonly InputAction m_Kloby_WASDMovement;
    private readonly InputAction m_Kloby_WASDPull;
    private readonly InputAction m_Kloby_WASDPush;
    private readonly InputAction m_Kloby_WASDboost;
    private readonly InputAction m_Kloby_ArrowsMovement;
    private readonly InputAction m_Kloby_ArrowsPush;
    private readonly InputAction m_Kloby_ArrowsPull;
    private readonly InputAction m_Kloby_Arrowsboost;
    private readonly InputAction m_Kloby_Quit;
    public struct KlobyActions
    {
        private @GameInput m_Wrapper;
        public KlobyActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @WASDMovement => m_Wrapper.m_Kloby_WASDMovement;
        public InputAction @WASDPull => m_Wrapper.m_Kloby_WASDPull;
        public InputAction @WASDPush => m_Wrapper.m_Kloby_WASDPush;
        public InputAction @WASDboost => m_Wrapper.m_Kloby_WASDboost;
        public InputAction @ArrowsMovement => m_Wrapper.m_Kloby_ArrowsMovement;
        public InputAction @ArrowsPush => m_Wrapper.m_Kloby_ArrowsPush;
        public InputAction @ArrowsPull => m_Wrapper.m_Kloby_ArrowsPull;
        public InputAction @Arrowsboost => m_Wrapper.m_Kloby_Arrowsboost;
        public InputAction @Quit => m_Wrapper.m_Kloby_Quit;
        public InputActionMap Get() { return m_Wrapper.m_Kloby; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KlobyActions set) { return set.Get(); }
        public void SetCallbacks(IKlobyActions instance)
        {
            if (m_Wrapper.m_KlobyActionsCallbackInterface != null)
            {
                @WASDMovement.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDMovement;
                @WASDMovement.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDMovement;
                @WASDMovement.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDMovement;
                @WASDPull.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDPull;
                @WASDPull.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDPull;
                @WASDPull.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDPull;
                @WASDPush.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDPush;
                @WASDPush.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDPush;
                @WASDPush.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDPush;
                @WASDboost.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDboost;
                @WASDboost.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDboost;
                @WASDboost.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnWASDboost;
                @ArrowsMovement.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsMovement;
                @ArrowsMovement.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsMovement;
                @ArrowsMovement.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsMovement;
                @ArrowsPush.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsPush;
                @ArrowsPush.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsPush;
                @ArrowsPush.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsPush;
                @ArrowsPull.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsPull;
                @ArrowsPull.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsPull;
                @ArrowsPull.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsPull;
                @Arrowsboost.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsboost;
                @Arrowsboost.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsboost;
                @Arrowsboost.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnArrowsboost;
                @Quit.started -= m_Wrapper.m_KlobyActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_KlobyActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_KlobyActionsCallbackInterface.OnQuit;
            }
            m_Wrapper.m_KlobyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @WASDMovement.started += instance.OnWASDMovement;
                @WASDMovement.performed += instance.OnWASDMovement;
                @WASDMovement.canceled += instance.OnWASDMovement;
                @WASDPull.started += instance.OnWASDPull;
                @WASDPull.performed += instance.OnWASDPull;
                @WASDPull.canceled += instance.OnWASDPull;
                @WASDPush.started += instance.OnWASDPush;
                @WASDPush.performed += instance.OnWASDPush;
                @WASDPush.canceled += instance.OnWASDPush;
                @WASDboost.started += instance.OnWASDboost;
                @WASDboost.performed += instance.OnWASDboost;
                @WASDboost.canceled += instance.OnWASDboost;
                @ArrowsMovement.started += instance.OnArrowsMovement;
                @ArrowsMovement.performed += instance.OnArrowsMovement;
                @ArrowsMovement.canceled += instance.OnArrowsMovement;
                @ArrowsPush.started += instance.OnArrowsPush;
                @ArrowsPush.performed += instance.OnArrowsPush;
                @ArrowsPush.canceled += instance.OnArrowsPush;
                @ArrowsPull.started += instance.OnArrowsPull;
                @ArrowsPull.performed += instance.OnArrowsPull;
                @ArrowsPull.canceled += instance.OnArrowsPull;
                @Arrowsboost.started += instance.OnArrowsboost;
                @Arrowsboost.performed += instance.OnArrowsboost;
                @Arrowsboost.canceled += instance.OnArrowsboost;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
            }
        }
    }
    public KlobyActions @Kloby => new KlobyActions(this);

    // Kloby1
    private readonly InputActionMap m_Kloby1;
    private IKloby1Actions m_Kloby1ActionsCallbackInterface;
    private readonly InputAction m_Kloby1_WASDMovement;
    private readonly InputAction m_Kloby1_WASDPull;
    private readonly InputAction m_Kloby1_WASDPush;
    private readonly InputAction m_Kloby1_WASDboost;
    private readonly InputAction m_Kloby1_ArrowsMovement;
    private readonly InputAction m_Kloby1_ArrowsPush;
    private readonly InputAction m_Kloby1_ArrowsPull;
    private readonly InputAction m_Kloby1_Arrowsboost;
    private readonly InputAction m_Kloby1_Quit;
    public struct Kloby1Actions
    {
        private @GameInput m_Wrapper;
        public Kloby1Actions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @WASDMovement => m_Wrapper.m_Kloby1_WASDMovement;
        public InputAction @WASDPull => m_Wrapper.m_Kloby1_WASDPull;
        public InputAction @WASDPush => m_Wrapper.m_Kloby1_WASDPush;
        public InputAction @WASDboost => m_Wrapper.m_Kloby1_WASDboost;
        public InputAction @ArrowsMovement => m_Wrapper.m_Kloby1_ArrowsMovement;
        public InputAction @ArrowsPush => m_Wrapper.m_Kloby1_ArrowsPush;
        public InputAction @ArrowsPull => m_Wrapper.m_Kloby1_ArrowsPull;
        public InputAction @Arrowsboost => m_Wrapper.m_Kloby1_Arrowsboost;
        public InputAction @Quit => m_Wrapper.m_Kloby1_Quit;
        public InputActionMap Get() { return m_Wrapper.m_Kloby1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Kloby1Actions set) { return set.Get(); }
        public void SetCallbacks(IKloby1Actions instance)
        {
            if (m_Wrapper.m_Kloby1ActionsCallbackInterface != null)
            {
                @WASDMovement.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDMovement;
                @WASDMovement.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDMovement;
                @WASDMovement.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDMovement;
                @WASDPull.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDPull;
                @WASDPull.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDPull;
                @WASDPull.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDPull;
                @WASDPush.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDPush;
                @WASDPush.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDPush;
                @WASDPush.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDPush;
                @WASDboost.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDboost;
                @WASDboost.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDboost;
                @WASDboost.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnWASDboost;
                @ArrowsMovement.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsMovement;
                @ArrowsMovement.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsMovement;
                @ArrowsMovement.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsMovement;
                @ArrowsPush.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsPush;
                @ArrowsPush.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsPush;
                @ArrowsPush.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsPush;
                @ArrowsPull.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsPull;
                @ArrowsPull.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsPull;
                @ArrowsPull.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsPull;
                @Arrowsboost.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsboost;
                @Arrowsboost.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsboost;
                @Arrowsboost.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnArrowsboost;
                @Quit.started -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_Kloby1ActionsCallbackInterface.OnQuit;
            }
            m_Wrapper.m_Kloby1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @WASDMovement.started += instance.OnWASDMovement;
                @WASDMovement.performed += instance.OnWASDMovement;
                @WASDMovement.canceled += instance.OnWASDMovement;
                @WASDPull.started += instance.OnWASDPull;
                @WASDPull.performed += instance.OnWASDPull;
                @WASDPull.canceled += instance.OnWASDPull;
                @WASDPush.started += instance.OnWASDPush;
                @WASDPush.performed += instance.OnWASDPush;
                @WASDPush.canceled += instance.OnWASDPush;
                @WASDboost.started += instance.OnWASDboost;
                @WASDboost.performed += instance.OnWASDboost;
                @WASDboost.canceled += instance.OnWASDboost;
                @ArrowsMovement.started += instance.OnArrowsMovement;
                @ArrowsMovement.performed += instance.OnArrowsMovement;
                @ArrowsMovement.canceled += instance.OnArrowsMovement;
                @ArrowsPush.started += instance.OnArrowsPush;
                @ArrowsPush.performed += instance.OnArrowsPush;
                @ArrowsPush.canceled += instance.OnArrowsPush;
                @ArrowsPull.started += instance.OnArrowsPull;
                @ArrowsPull.performed += instance.OnArrowsPull;
                @ArrowsPull.canceled += instance.OnArrowsPull;
                @Arrowsboost.started += instance.OnArrowsboost;
                @Arrowsboost.performed += instance.OnArrowsboost;
                @Arrowsboost.canceled += instance.OnArrowsboost;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
            }
        }
    }
    public Kloby1Actions @Kloby1 => new Kloby1Actions(this);
    public interface IKlobyActions
    {
        void OnWASDMovement(InputAction.CallbackContext context);
        void OnWASDPull(InputAction.CallbackContext context);
        void OnWASDPush(InputAction.CallbackContext context);
        void OnWASDboost(InputAction.CallbackContext context);
        void OnArrowsMovement(InputAction.CallbackContext context);
        void OnArrowsPush(InputAction.CallbackContext context);
        void OnArrowsPull(InputAction.CallbackContext context);
        void OnArrowsboost(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
    }
    public interface IKloby1Actions
    {
        void OnWASDMovement(InputAction.CallbackContext context);
        void OnWASDPull(InputAction.CallbackContext context);
        void OnWASDPush(InputAction.CallbackContext context);
        void OnWASDboost(InputAction.CallbackContext context);
        void OnArrowsMovement(InputAction.CallbackContext context);
        void OnArrowsPush(InputAction.CallbackContext context);
        void OnArrowsPull(InputAction.CallbackContext context);
        void OnArrowsboost(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
    }
}
